#!/bin/bash

# This script setup tmux layout which I usually use
# while working on Ruby on Rails projects:
#  * first window runs Rails server and watches log-file;
#  * second window runs git-sh + Guard + Rails console.


CURRENT_DIR=${PWD##*/}
TMUX_SESSION=$CURRENT_DIR

# Check if session already exists
EXISTS=`tmux has-session -t "$TMUX_SESSION" 2> /dev/null && echo 'yes'`
if [ $EXISTS ]
then
  tmux -2 attach-session -t "$TMUX_SESSION"
  exit
fi

# Server start command
if [ -f 'Procfile' ]
then
  SERVER_START='foreman s'
else
  SERVER_START='rails s'
fi

# Guard
GUARD_START=''
if [ -f 'Guardfile' ]
then
  GUARD_START='guard'
fi

# Log file
LOG_FILE=''
LOG_FILES=('log/development-nostdout.log' 'log/development.log')
for log_file in ${LOG_FILES[@]}
do
  if [ -f $log_file ]
  then
    LOG_FILE=$log_file
    break
  fi
done

# Start tmux
tmux -2 new-session -d -s "$TMUX_SESSION"

# Rename 1st window and start Rails server
tmux rename-window 'Server'
tmux send-keys "$SERVER_START" C-m

# Watch log-file
if [ $LOG_FILE ]
then
  tmux split-window -v
  tmux select-pane -t 2
  tmux send-keys "tail -f \"$LOG_FILE\"" C-m
fi

# Create 2nd window and run git-sh in it
tmux new-window -t "$TMUX_SESSION:2" -n 'Shell' 'git-sh'
tmux select-window -t "$TMUX_SESSION:2"

# Start Rails console
tmux split-window -v
tmux select-pane -t 2
tmux send-keys 'rails c' C-m

# Start Guard
if [ $GUARD_START ]
then
  tmux select-pane -t 1
  tmux split-window -h
  tmux select-pane -t 2
  tmux send-keys 'guard' C-m
fi

# Attach to tmux session
tmux select-window -t "$TMUX_SESSION:2"
tmux -2 attach-session -t "$TMUX_SESSION"
